name: Python Lint with Pylint

# Trigger the workflow on push or pull request events for the main branch
on:
  push:
    branches:
      - ["main", "master" ] 
  pull_request:
    branches:
      - ["main", "master" ] 

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version to use

    # Step 3: Install project dependencies (if you have a requirements.txt file)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run Pylint
    - name: Run Pylint
      run: |
        pylint your_project_directory/ > pylint_report.txt || true

    # Step 5: Upload the Pylint report as an artifact
    - name: Upload Pylint Report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.txt